[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "^1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "=2.2.1"
